# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on: [push, pull_request] # this may be overkill, depends on how often we want tests to run

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x] # this may all be irrelevant since we're using `yarn`, maybe check `yarn` version
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      
      - name: Installing
        run: |
          echo Installing yarn
          yarn install
          yarn -v
      
      - name: Testing
        run: |
          echo Running all tests in *test.js files
          yarn test --watchAll=false
      
      - name: Building
        if: ${{ success() && github.event_name == 'pull_request' }}
        run: |
          echo Testing ran successfully so this pull request is building
          yarn build


# default settings, kept for reference
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Use Node.js ${{ matrix.node-version }}
#      uses: actions/setup-node@v1
#      with:
#        node-version: ${{ matrix.node-version }}
#    - run: npm ci
#    - run: npm run build --if-present
#   - run: npm test
