# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Installing Dependencies
        run: |
          echo Installing dependencies
          npm install

      - name: Configuring Git
        run: |
          echo Setting workflow git configuration to use Jakes account
          git config user.email "jakeod99@gmail.com"
          git config user.name "Jake O'Donnell"

      - name: Deploying
        run: |
          echo Deploying to GitHub Pages
          npm run deploy
