# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  push:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Installing Dependencies
        run: |
          echo Installing dependencies
          npm install

      - name: Deploying
        run: |
          echo Setting workflow git configuration to use Jakes account
          git config --global user.email "jakeod99@gmail.com"
          git config --global user.name "Jake O'Donnell"
          git remote set-url origin https://${{ secrets.DEPLOY_ACCESS_TOKEN }}@github.com/${{ github.repository }}
          echo Deploying to GitHub Pages
          npm run deploy
